class CountryModel {
  final String name;
  final String code;
  final String flag;

  CountryModel({
    required this.name,
    required this.code,
    required this.flag,
  });
}

class AppCountries {
  static List<CountryModel> getCountries() {
    return [
      CountryModel(name: 'كل الدول (Global)', code: 'ALL', flag: '🌍'),
      CountryModel(name: 'اليمن', code: '+967', flag: '🇾🇪'),
      CountryModel(name: 'المملكة العربية السعودية', code: '+966', flag: '🇸🇦'),
      CountryModel(name: 'الإمارات العربية المتحدة', code: '+971', flag: '🇦🇪'),
      CountryModel(name: 'مصر', code: '+20', flag: '🇪🇬'),
      CountryModel(name: 'الكويت', code: '+965', flag: '🇰🇼'),
      CountryModel(name: 'قطر', code: '+974', flag: '🇶🇦'),
      CountryModel(name: 'البحرين', code: '+973', flag: '🇧🇭'),
      CountryModel(name: 'عومان', code: '+968', flag: '🇴🇲'),
      CountryModel(name: 'الأردن', code: '+962', flag: '🇯🇴'),
      CountryModel(name: 'العراق', code: '+964', flag: '🇮🇶'),
      CountryModel(name: 'سوريا', code: '+963', flag: '🇸🇾'),
      CountryModel(name: 'لبنان', code: '+961', flag: '🇱🇧'),
      CountryModel(name: 'فلسطين', code: '+970', flag: '🇵🇸'),
      CountryModel(name: 'المغرب', code: '+212', flag: '🇲🇦'),
      CountryModel(name: 'الجزائر', code: '+213', flag: '🇩🇿'),
      CountryModel(name: 'تونس', code: '+216', flag: '🇹🇳'),
      CountryModel(name: 'ليبيا', code: '+218', flag: '🇱🇾'),
      CountryModel(name: 'السودان', code: '+249', flag: '🇸🇩'),
      CountryModel(name: 'الصومال', code: '+252', flag: '🇸🇴'),
      CountryModel(name: 'جيبوتي', code: '+253', flag: '🇩🇯'),
      CountryModel(name: 'موريتانيا', code: '+222', flag: '🇲🇷'),
      CountryModel(name: 'جزر القمر', code: '+269', flag: '🇰🇲'),
      CountryModel(name: 'الولايات المتحدة', code: '+1', flag: '🇺🇸'),
      CountryModel(name: 'كندا', code: '+1', flag: '🇨🇦'),
      CountryModel(name: 'المملكة المتحدة', code: '+44', flag: '🇬🇧'),
      CountryModel(name: 'فرنسا', code: '+33', flag: '🇫🇷'),
      CountryModel(name: 'ألمانيا', code: '+49', flag: '🇩🇪'),
      CountryModel(name: 'إيطاليا', code: '+39', flag: '🇮🇹'),
      CountryModel(name: 'إسبانيا', code: '+34', flag: '🇪🇸'),
      CountryModel(name: 'تركيا', code: '+90', flag: '🇹🇷'),
      CountryModel(name: 'روسيا', code: '+7', flag: '🇷🇺'),
      CountryModel(name: 'الصين', code: '+86', flag: '🇨🇳'),
      CountryModel(name: 'اليابان', code: '+81', flag: '🇯🇵'),
      CountryModel(name: 'كوريا الجنوبية', code: '+82', flag: '🇰🇷'),
      CountryModel(name: 'الهند', code: '+91', flag: '🇮🇳'),
      CountryModel(name: 'باكستان', code: '+92', flag: '🇵🇰'),
      CountryModel(name: 'بنغلاديش', code: '+880', flag: '🇧🇩'),
      CountryModel(name: 'إندونيسيا', code: '+62', flag: '🇮🇩'),
      CountryModel(name: 'ماليزيا', code: '+60', flag: '🇲🇾'),
      CountryModel(name: 'سنغافورة', code: '+65', flag: '🇸🇬'),
      CountryModel(name: 'تايلاند', code: '+66', flag: '🇹🇭'),
      CountryModel(name: 'فيتنام', code: '+84', flag: '🇻🇳'),
      CountryModel(name: 'الفلبين', code: '+63', flag: '🇵🇭'),
      CountryModel(name: 'أستراليا', code: '+61', flag: '🇦🇺'),
      CountryModel(name: 'نيوزيلندا', code: '+64', flag: '🇳🇿'),
      CountryModel(name: 'البرازيل', code: '+55', flag: '🇧🇷'),
      CountryModel(name: 'الأرجنتين', code: '+54', flag: '🇦🇷'),
      CountryModel(name: 'المكسيك', code: '+52', flag: '🇲🇽'),
      CountryModel(name: 'كولومبيا', code: '+57', flag: '🇨🇴'),
      CountryModel(name: 'تشيلي', code: '+56', flag: '🇨🇱'),
      CountryModel(name: 'جنوب إفريقيا', code: '+27', flag: '🇿🇦'),
      CountryModel(name: 'نيجيريا', code: '+234', flag: '🇳🇬'),
      CountryModel(name: 'كينيا', code: '+254', flag: '🇰🇪'),
      CountryModel(name: 'إثيوبيا', code: '+251', flag: '🇪🇹'),
      CountryModel(name: 'غانا', code: '+233', flag: '🇬🇭'),
      CountryModel(name: 'إيران', code: '+98', flag: '🇮🇷'),
      CountryModel(name: 'أفغانستان', code: '+93', flag: '🇦🇫'),
      CountryModel(name: 'ألبانيا', code: '+355', flag: '🇦🇱'),
      CountryModel(name: 'أندورا', code: '+376', flag: '🇦🇩'),
      CountryModel(name: 'أنغولا', code: '+244', flag: '🇦🇴'),
      CountryModel(name: 'أنتيغوا وباربودا', code: '+1268', flag: '🇦🇬'),
      CountryModel(name: 'أرمينيا', code: '+374', flag: '🇦🇲'),
      CountryModel(name: 'النمسا', code: '+43', flag: '🇦🇹'),
      CountryModel(name: 'أذربيجان', code: '+994', flag: '🇦🇿'),
      CountryModel(name: 'بهاماس', code: '+1242', flag: '🇧🇸'),
      CountryModel(name: 'باربادوس', code: '+1246', flag: '🇧🇧'),
      CountryModel(name: 'بلاروسيا', code: '+375', flag: '🇧🇾'),
      CountryModel(name: 'بلجيكا', code: '+32', flag: '🇧🇪'),
      CountryModel(name: 'بليز', code: '+501', flag: '🇧🇿'),
      CountryModel(name: 'بنين', code: '+229', flag: '🇧🇯'),
      CountryModel(name: 'بوتان', code: '+975', flag: '🇧🇹'),
      CountryModel(name: 'بوليفيا', code: '+591', flag: '🇧🇴'),
      CountryModel(name: 'البوسنة والهرسك', code: '+387', flag: '🇧🇦'),
      CountryModel(name: 'بوتسوانا', code: '+267', flag: '🇧🇼'),
      CountryModel(name: 'بروناي', code: '+673', flag: '🇧🇳'),
      CountryModel(name: 'بلغاريا', code: '+359', flag: '🇧🇬'),
      CountryModel(name: 'بوركينا فاسو', code: '+226', flag: '🇧🇫'),
      CountryModel(name: 'بوروندي', code: '+257', flag: '🇧🇮'),
      CountryModel(name: 'كمبوديا', code: '+855', flag: '🇰🇭'),
      CountryModel(name: 'كاميرون', code: '+237', flag: '🇨🇲'),
      CountryModel(name: 'الرأس الأخضر', code: '+238', flag: '🇨🇻'),
      CountryModel(name: 'جمهورية أفريقيا الوسطى', code: '+236', flag: '🇨🇫'),
      CountryModel(name: 'تشاد', code: '+235', flag: '🇹🇩'),
      CountryModel(name: 'كوستاريكا', code: '+506', flag: '🇨🇷'),
      CountryModel(name: 'ساحل العاج', code: '+225', flag: '🇨🇮'),
      CountryModel(name: 'كرواتيا', code: '+385', flag: '🇭🇷'),
      CountryModel(name: 'وبا', code: '+53', flag: '🇨🇺'),
      CountryModel(name: 'قبرص', code: '+357', flag: '🇨🇾'),
      CountryModel(name: 'التشيك', code: '+420', flag: '🇨🇿'),
      CountryModel(name: 'الدنمارك', code: '+45', flag: '🇩🇰'),
      CountryModel(name: 'دومينيكا', code: '+1767', flag: '🇩🇲'),
      CountryModel(name: 'جمهورية الدومينيكان', code: '+1809', flag: '🇩🇴'),
      CountryModel(name: 'الإكوادور', code: '+593', flag: '🇪🇨'),
      CountryModel(name: 'السلفادور', code: '+503', flag: '🇸🇻'),
      CountryModel(name: 'غينيا الاستوائية', code: '+240', flag: '🇬🇶'),
      CountryModel(name: 'إريتريا', code: '+291', flag: '🇪🇷'),
      CountryModel(name: 'إستونيا', code: '+372', flag: '🇪🇪'),
      CountryModel(name: 'إسواتيني', code: '+268', flag: '🇸🇿'),
      CountryModel(name: 'فيجي', code: '+679', flag: '🇫🇯'),
      CountryModel(name: 'فنلندا', code: '+358', flag: '🇫🇮'),
      CountryModel(name: 'الغابون', code: '+241', flag: '🇬🇦'),
      CountryModel(name: 'غامبيا', code: '+220', flag: '🇬🇲'),
      CountryModel(name: 'جورجيا', code: '+995', flag: '🇬🇪'),
      CountryModel(name: 'غانا', code: '+233', flag: '🇬🇭'),
      CountryModel(name: 'اليونان', code: '+30', flag: '🇬🇷'),
      CountryModel(name: 'غرينادا', code: '+1473', flag: '🇬🇩'),
      CountryModel(name: 'غواتيمالا', code: '+502', flag: '🇬🇹'),
      CountryModel(name: 'غينيا', code: '+224', flag: '🇬🇳'),
      CountryModel(name: 'غينيا بيساو', code: '+245', flag: '🇬🇼'),
      CountryModel(name: 'غيانا', code: '+592', flag: '🇬🇾'),
      CountryModel(name: 'هايتي', code: '+509', flag: '🇭🇹'),
      CountryModel(name: 'هندوراس', code: '+504', flag: '🇭🇳'),
      CountryModel(name: 'المجر', code: '+36', flag: '🇭🇺'),
      CountryModel(name: 'آيسلندا', code: '+354', flag: '🇮🇸'),
      CountryModel(name: 'إيرلندا', code: '+353', flag: '🇮🇪'),
      CountryModel(name: 'إسرائيل', code: '+972', flag: '🇮🇱'),
      CountryModel(name: 'جامايكا', code: '+1876', flag: '🇯🇲'),
      CountryModel(name: 'كازاخستان', code: '+7', flag: '🇰🇿'),
      CountryModel(name: 'كيريباتي', code: '+686', flag: '🇰🇮'),
      CountryModel(name: 'قيرغيزستان', code: '+996', flag: '🇰🇬'),
      CountryModel(name: 'لاوس', code: '+856', flag: '🇱🇦'),
      CountryModel(name: 'لاتفيا', code: '+371', flag: '🇱🇻'),
      CountryModel(name: 'ليسوتو', code: '+266', flag: '🇱🇸'),
      CountryModel(name: 'ليبيريا', code: '+231', flag: '🇱🇷'),
      CountryModel(name: 'ليختنشتاين', code: '+423', flag: '🇱🇮'),
      CountryModel(name: 'ليتوانيا', code: '+370', flag: '🇱🇹'),
      CountryModel(name: 'لوكسمبورغ', code: '+352', flag: '🇱🇺'),
      CountryModel(name: 'مدغشقر', code: '+261', flag: '🇲🇬'),
      CountryModel(name: 'مالاوى', code: '+265', flag: '🇲🇼'),
      CountryModel(name: 'المالديف', code: '+960', flag: '🇲🇻'),
      CountryModel(name: 'مالي', code: '+223', flag: '🇲🇱'),
      CountryModel(name: 'مالطا', code: '+356', flag: '🇲🇹'),
      CountryModel(name: 'جزر مارشال', code: '+692', flag: '🇲🇭'),
      CountryModel(name: 'موريشيوس', code: '+230', flag: '🇲🇺'),
      CountryModel(name: 'ميكرونيزيا', code: '+691', flag: '🇫🇲'),
      CountryModel(name: 'مولدوفا', code: '+373', flag: '🇲🇩'),
      CountryModel(name: 'موناكو', code: '+377', flag: '🇲🇨'),
      CountryModel(name: 'منغوليا', code: '+976', flag: '🇲🇳'),
      CountryModel(name: 'الجبل الأسود', code: '+382', flag: '🇲🇪'),
      CountryModel(name: 'موزمبيق', code: '+258', flag: '🇲🇿'),
      CountryModel(name: 'ميانمار', code: '+95', flag: '🇲🇲'),
      CountryModel(name: 'ناميبيا', code: '+264', flag: '🇳🇦'),
      CountryModel(name: 'ناورو', code: '+674', flag: '🇳🇷'),
      CountryModel(name: 'نيبال', code: '+977', flag: '🇳🇵'),
      CountryModel(name: 'هولندا', code: '+31', flag: '🇳🇱'),
      CountryModel(name: 'نيكاراغوا', code: '+505', flag: '🇳🇮'),
      CountryModel(name: 'النيجر', code: '+227', flag: '🇳🇪'),
      CountryModel(name: 'كوريا الشمالية', code: '+850', flag: '🇰🇵'),
      CountryModel(name: 'مقدونيا الشمالية', code: '+389', flag: '🇲🇰'),
      CountryModel(name: 'النرويج', code: '+47', flag: '🇳🇴'),
      CountryModel(name: 'بالاو', code: '+680', flag: '🇵🇼'),
      CountryModel(name: 'بنما', code: '+507', flag: '🇵🇦'),
      CountryModel(name: 'بابوا غينيا الجديدة', code: '+675', flag: '🇵🇬'),
      CountryModel(name: 'باراغواي', code: '+595', flag: '🇵🇾'),
      CountryModel(name: 'بيرو', code: '+51', flag: '🇵🇪'),
      CountryModel(name: 'بولندا', code: '+48', flag: '🇵🇱'),
      CountryModel(name: 'البرتغال', code: '+351', flag: '🇵🇹'),
      CountryModel(name: 'رومانيا', code: '+40', flag: '🇷🇴'),
      CountryModel(name: 'رواندا', code: '+250', flag: '🇷🇼'),
      CountryModel(name: 'سانت كيتس ونيفيس', code: '+1869', flag: '🇰🇳'),
      CountryModel(name: 'سانت لوسيا', code: '+1758', flag: '🇱🇨'),
      CountryModel(name: 'ساموا', code: '+685', flag: '🇼🇸'),
      CountryModel(name: 'سان مارينو', code: '+378', flag: '🇸🇲'),
      CountryModel(name: 'ساو تومي وبرينسيب', code: '+239', flag: '🇸🇹'),
      CountryModel(name: 'السنغال', code: '+221', flag: '🇸🇳'),
      CountryModel(name: 'صربيا', code: '+381', flag: '🇷🇸'),
      CountryModel(name: 'سيشل', code: '+248', flag: '🇸🇨'),
      CountryModel(name: 'سيراليون', code: '+232', flag: '🇸🇱'),
      CountryModel(name: 'سلوفاكيا', code: '+421', flag: '🇸🇰'),
      CountryModel(name: 'سلوفينيا', code: '+386', flag: '🇸🇮'),
      CountryModel(name: 'جزر سليمان', code: '+677', flag: '🇸🇧'),
      CountryModel(name: 'جنوب السودان', code: '+211', flag: '🇸🇸'),
      CountryModel(name: 'سريلانكا', code: '+94', flag: '🇱🇰'),
      CountryModel(name: 'سورينام', code: '+597', flag: '🇸🇷'),
      CountryModel(name: 'السويد', code: '+46', flag: '🇸🇪'),
      CountryModel(name: 'سويسرا', code: '+41', flag: '🇨🇭'),
      CountryModel(name: 'طاجيكستان', code: '+992', flag: '🇹🇯'),
      CountryModel(name: 'تانزانيا', code: '+255', flag: '🇹🇿'),
      CountryModel(name: 'تيمور الشرقية', code: '+670', flag: '🇹🇱'),
      CountryModel(name: 'توغو', code: '+228', flag: '🇹🇬'),
      CountryModel(name: 'تونغا', code: '+676', flag: '🇹🇴'),
      CountryModel(name: 'ترينيداد وتوباغو', code: '+1868', flag: '🇹🇹'),
      CountryModel(name: 'تركمانستان', code: '+993', flag: '🇹🇲'),
      CountryModel(name: 'توفالو', code: '+688', flag: '🇹🇻'),
      CountryModel(name: 'أوغندا', code: '+256', flag: '🇺🇬'),
      CountryModel(name: 'أوكرانيا', code: '+380', flag: '🇺🇦'),
      CountryModel(name: 'أوروغواي', code: '+598', flag: '🇺🇾'),
      CountryModel(name: 'أوزبكستان', code: '+998', flag: '🇺🇿'),
      CountryModel(name: 'فانواتو', code: '+678', flag: '🇻🇺'),
      CountryModel(name: 'الفาтиكان', code: '+379', flag: '🇻🇦'),
      CountryModel(name: 'فنزويلا', code: '+58', flag: '🇻🇪'),
      CountryModel(name: 'زامبيا', code: '+260', flag: '🇿🇲'),
      CountryModel(name: 'زيمبابوي', code: '+263', flag: '🇿🇼'),
    ];
  }
}
