# force-rebuild-timestamp-2026-08-09
# force refresh build 2026
name: mobile_empire_app
description: AymnGuard Enterprise Sovereign Super App Engine.
publish_to: 'none'
version: 18.7.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  qr_flutter: ^4.1.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0  # أضف هذا السطر لتمكين الاتصال بالباكن إند

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
# force refresh

