version: '3.8'

services:
  aymnguard_core:
    build:
      context: ./backend_core
    container_name: aymnguard_core_app
    restart: always
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - aymnguard-network

networks:
  aymnguard-network:
    driver: bridge
